version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: cert_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_volume:/data/db

  api:
    image: cert_api
    build: 
      context: backend
      dockerfile: ./dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  ui:
    image: cert_ui
    build:
      context: frontend
      dockerfile: ./dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mongo_volume:
